global using IVoice.Data;
global using IVoice.Models;
global using IVoice.Reopsitories;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using IVoice.Settings;
global using IVoice.Attributes;
global using IVoice.ViewModel;
global using Microsoft.AspNetCore.Http;